# source("https://bioconductor.org/biocLite.R")
# biocLite("myvariant")
# install.packages("devtools")
# devtools::install_github("slowkow/proxysnps")
library(proxysnps)
d <- get_proxies(query = "rs42")
plot(d$POS, d$R.squared, main="rs42", xlab="Position", ylab=bquote("R"^2))